name: graspness
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy=1.24.4
  - scipy=1.10.1
  - matplotlib=3.7.4
  - pandas=2.0.3
  - cython=3.0.8
  - ninja=1.11.1.1
  - pillow=10.2.0
  - pip:
      - open3d==0.18.0
      - openmim==0.3.9
      - opencv-python==4.9.0.80
      - graspnetapi==1.2.11
      - grasp-nms==1.0.2
      - pytorch-lightning==0.7.1
      - trimesh==3.9.32
      - pyquaternion==0.9.9
      - tensorboard==2.14.0
      - tensorboardx==2.6.2.2
      - tqdm==4.62.3
      - addict==2.4.0
      - pyyaml==6.0
      - imageio==2.10.5
      - matplotlib-inline==0.1.3
      - jsonschema==3.2.0
      - transforms3d==0.3.1