gn_root: "/media/dsp520/Grasp_2T/graspnet"
comap_root: '/media/user/DATA/'
camera: "realsense"
log: "logs"
logging_step: 100
validation_interval: 1 # Save and valid have same interval
checkpoints: "checkpoints"

batch_size: 28
val_batch_size: 36
lr: 0.001
PLUS: True

hmin: 256
hmax: 480
wmin: 256
wmax: 640
size_int: 8


